/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.MySqlDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import java.util.ArrayList;
import model.NewStaff;

/**
 *
 * @author Shazana Affandi
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        show_NewStaff();
    }

    public ArrayList<NewStaff> newStaffList()
    {
        ArrayList<NewStaff> staffList = new ArrayList<>();
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "SELECT * FROM staff_table";
        try {
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery(query);
        
        NewStaff newStaff;
        while(rs.next())
        {
            newStaff = new NewStaff(rs.getString("staffID"), rs.getString("startingDate"), rs.getString("icNumber"), rs.getString("name"), rs.getString("gender"), rs.getString("position"), rs.getString("username"), rs.getString("password"), rs.getString("address"), rs.getString("phoneNumber"), rs.getString("emailAddress"));
            staffList.add(newStaff);
        }
        }catch(Exception e)
         {
           JOptionPane.showMessageDialog(null, e);
         }
        return staffList;
    }
    
    public void show_NewStaff()
    {
        ArrayList<NewStaff> list = newStaffList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[11];
        for(int i=0; i<list.size(); i++)
        {
            row[0] = list.get(i).getStaffID();
            row[1] = list.get(i).getStartingDate();
            row[2] = list.get(i).getIcNumber();
            row[3] = list.get(i).getName();
            row[4] = list.get(i).getGender();
            row[5] = list.get(i).getPosition();
            row[6] = list.get(i).getUsername();
            row[7] = list.get(i).getPassword();
            row[8] = list.get(i).getAddress();
            row[9] = list.get(i).getPhoneNumber();
            row[10] = list.get(i).getEmailAddress();
            model.addRow(row);   
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jlblStaffID = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        jlblName = new javax.swing.JLabel();
        jlblIcNum = new javax.swing.JLabel();
        jlblGender = new javax.swing.JLabel();
        jlblPosition = new javax.swing.JLabel();
        jlblUsername = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jlblAddress = new javax.swing.JLabel();
        jlblPhone = new javax.swing.JLabel();
        jlblEmail = new javax.swing.JLabel();
        jTxtPhone = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jlblRetype = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jRetypePassword = new javax.swing.JPasswordField();
        jTxtICNum = new javax.swing.JTextField();
        jTxtDate = new javax.swing.JTextField();
        jTxtStaffID = new javax.swing.JTextField();
        jRadBtnMale = new javax.swing.JRadioButton();
        jRadBtnFemale = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBtnAdd = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jBtnUpdate = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jlblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jlblTitle.setText("NEW STAFF REGISTRATION");

        jlblStaffID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblStaffID.setText("Staff ID");

        jlblDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDate.setText("Starting Date");

        jlblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblName.setText("Staff Name");

        jlblIcNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblIcNum.setText("IC Number");

        jlblGender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblGender.setText("Gender");

        jlblPosition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPosition.setText("Position");

        jlblUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblUsername.setText("Username");

        jlblPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPassword.setText("Password");

        jlblAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblAddress.setText("Home Address");

        jlblPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPhone.setText("Phone Number");

        jlblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblEmail.setText("Email Address");

        jTxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPhoneActionPerformed(evt);
            }
        });

        jTxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAddressActionPerformed(evt);
            }
        });

        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });

        jTxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsernameActionPerformed(evt);
            }
        });

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jlblRetype.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblRetype.setText("Re-Type Password");

        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jRetypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetypePasswordActionPerformed(evt);
            }
        });

        jTxtICNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtICNumActionPerformed(evt);
            }
        });

        jTxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDateActionPerformed(evt);
            }
        });

        jTxtStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtStaffIDActionPerformed(evt);
            }
        });

        jRadBtnMale.setBackground(new java.awt.Color(0, 204, 204));
        jRadBtnMale.setText("Male");
        jRadBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtnMaleActionPerformed(evt);
            }
        });

        jRadBtnFemale.setBackground(new java.awt.Color(0, 204, 204));
        jRadBtnFemale.setText("Female");
        jRadBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtnFemaleActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Admin", "Dentist", "Nurse" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnAdd.setText("INSERT");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnBack.setBackground(new java.awt.Color(0, 0, 204));
        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBack.setText("BACK");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("(including alphabet and number, eg: A000)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("(yyyy/mm/dd)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("(excluding '-' symbol)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setText("(excluding '-' symbol)");

        jBtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnUpdate.setText("UPDATE");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnDelete.setText("DELETE");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "staffID", "startingDate", "icNumber", "name", "gender", "position", "username", "password", "address", "phoneNumber", "emailAddress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jlblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnAdd)
                                .addGap(40, 40, 40)
                                .addComponent(jBtnUpdate)
                                .addGap(40, 40, 40)
                                .addComponent(jBtnDelete)
                                .addGap(37, 37, 37)
                                .addComponent(jBtnBack)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblGender)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblPosition)
                                            .addComponent(jlblUsername)
                                            .addComponent(jlblPassword)
                                            .addComponent(jlblRetype)
                                            .addComponent(jlblAddress)
                                            .addComponent(jlblPhone)
                                            .addComponent(jlblName)
                                            .addComponent(jlblIcNum)
                                            .addComponent(jlblDate)
                                            .addComponent(jlblStaffID)
                                            .addComponent(jlblEmail))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTxtDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                    .addComponent(jTxtStaffID, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jRadBtnMale)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jRadBtnFemale)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTxtICNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16))
                                            .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17))
                                            .addComponent(jRetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(10, 10, 10)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlblTitle)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jlblStaffID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jlblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtICNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jlblIcNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadBtnMale)
                            .addComponent(jRadBtnFemale)
                            .addComponent(jlblGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblRetype))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPhone)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnBack)
                            .addComponent(jBtnDelete)
                            .addComponent(jBtnUpdate)
                            .addComponent(jBtnAdd)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String Gender;
    
    private void jTxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPhoneActionPerformed
        jTxtPhone.setText(null);
    }//GEN-LAST:event_jTxtPhoneActionPerformed

    private void jTxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAddressActionPerformed
        jTxtAddress.setText(null);
    }//GEN-LAST:event_jTxtAddressActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        jTxtEmail.setText(null);
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jTxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsernameActionPerformed
        jTxtUsername.setText(null);
    }//GEN-LAST:event_jTxtUsernameActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        jPassword.setText(null);
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        jTxtName.setText(null);
    }//GEN-LAST:event_jTxtNameActionPerformed

    private void jRetypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetypePasswordActionPerformed
        jRetypePassword.setText(null);
    }//GEN-LAST:event_jRetypePasswordActionPerformed

    private void jTxtICNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtICNumActionPerformed
        jTxtICNum.setText(null);
    }//GEN-LAST:event_jTxtICNumActionPerformed

    private void jTxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDateActionPerformed
        jTxtDate.setText(null);
    }//GEN-LAST:event_jTxtDateActionPerformed

    private void jRadBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtnMaleActionPerformed
        Gender = "Male";
    }//GEN-LAST:event_jRadBtnMaleActionPerformed

    private void jRadBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtnFemaleActionPerformed
        Gender = "Female";
    }//GEN-LAST:event_jRadBtnFemaleActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "INSERT INTO staff_table(staffID, startingDate, icNumber, name, gender, position, username, password, address, phoneNumber, emailAddress) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        String Password = new String(jPassword.getPassword());
        String Confirm = new String(jRetypePassword.getPassword());

        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jTxtStaffID.getText());
            ps.setString(2, jTxtDate.getText());
            ps.setString(3, jTxtICNum.getText());
            ps.setString(4, jTxtName.getText());

            if(jRadBtnMale.isSelected())
            {
                Gender = "Male";
            }
            if(jRadBtnFemale.isSelected())
            {
                Gender = "Female";
            }
            ps.setString(5, Gender);

            ps.setString(6, (String) jComboBox1.getSelectedItem());
            ps.setString(7, jTxtUsername.getText());

            ps.setString(8, Password);
            ps.setString(8, Confirm);

            ps.setString(9, jTxtAddress.getText());
            ps.setString(10, jTxtPhone.getText());
            ps.setString(11, jTxtEmail.getText());

            if(Password.equals(Confirm))
            {
                ps.execute();
                ps.close();

                JOptionPane.showMessageDialog(null, "Your username and password already saved!");
                JOptionPane.showMessageDialog(null, "Successfully adding new staff's data!");

                AdminPage adminPage = new AdminPage();
                adminPage.setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Your Password does not match.");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        if(jTxtStaffID.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection conn = MySqlDatabase.ConnectDB();
            String Password = new String(jPassword.getPassword());
            String Confirm = new String(jRetypePassword.getPassword());

            try {
                UpdateQuery = "UPDATE staff_table SET startingDate = ?, icNumber = ?, name = ?, gender = ?, position = ?, username = ?, password = ?, address = ?, phoneNumber = ?, emailAddress = ? WHERE staffID = ?";
                ps = conn.prepareStatement(UpdateQuery);
                ps.setString(1, jTxtDate.getText());
                ps.setString(2, jTxtICNum.getText());
                ps.setString(3, jTxtName.getText());

                if(jRadBtnMale.isSelected())
                {
                    Gender = "Male";
                }
                if(jRadBtnFemale.isSelected())
                {
                    Gender = "Female";
                }
                ps.setString(4, Gender);

                ps.setString(5, (String) jComboBox1.getSelectedItem());
                ps.setString(6, jTxtUsername.getText());

                ps.setString(7, Password);
                ps.setString(7, Confirm);

                ps.setString(8, jTxtAddress.getText());
                ps.setString(9, jTxtPhone.getText());
                ps.setString(10, jTxtEmail.getText());

                ps.setString(11, jTxtStaffID.getText());

                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Staff's data updated");
                
                AdminPage adminPage = new AdminPage();
                adminPage.setVisible(true);
                dispose();
            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "DELETE FROM staff_table WHERE staffID = ?";
        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jTxtStaffID.getText());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Successfully deleted the data.");
            
            AdminPage adminPage = new AdminPage();
            adminPage.setVisible(true);
            dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        jTxtStaffID.setText(model.getValueAt(i,0).toString());
        jTxtDate.setText(model.getValueAt(i,1).toString());
        jTxtICNum.setText(model.getValueAt(i,2).toString());
        jTxtName.setText(model.getValueAt(i,3).toString());
        String Gender = model.getValueAt(i,4).toString();
        if (Gender.equals("Male"))
        {
            jRadBtnMale.setSelected(true);
            jRadBtnFemale.setSelected(false);
        }
        else
        {
            jRadBtnFemale.setSelected(true);
            jRadBtnMale.setSelected(false);
        }
        String position = model.getValueAt(i,5).toString();
        switch(position)
        {
            case "Admin":
            jComboBox1.setSelectedIndex(1);
            break;
            case "Dentist":
            jComboBox1.setSelectedIndex(2);
            break;
            case "Nurse":
            jComboBox1.setSelectedIndex(3);
            break;
        }
        jTxtUsername.setText(model.getValueAt(i,6).toString());
        jPassword.setText(model.getValueAt(i,7).toString());
        jRetypePassword.setText(model.getValueAt(i,7).toString());
        jTxtAddress.setText(model.getValueAt(i,8).toString());
        jTxtPhone.setText(model.getValueAt(i,9).toString());
        jTxtEmail.setText(model.getValueAt(i,10).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTxtStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtStaffIDActionPerformed
        jTxtStaffID.setText(null);
    }//GEN-LAST:event_jTxtStaffIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JRadioButton jRadBtnFemale;
    private javax.swing.JRadioButton jRadBtnMale;
    private javax.swing.JPasswordField jRetypePassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtDate;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtICNum;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtPhone;
    private javax.swing.JTextField jTxtStaffID;
    private javax.swing.JTextField jTxtUsername;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblGender;
    private javax.swing.JLabel jlblIcNum;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblPhone;
    private javax.swing.JLabel jlblPosition;
    private javax.swing.JLabel jlblRetype;
    private javax.swing.JLabel jlblStaffID;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlblUsername;
    // End of variables declaration//GEN-END:variables
}
