/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import database.MySqlDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import javax.swing.table.TableModel;
import model.Medicines;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Shazana Affandi
 */
public class MedicineForm extends javax.swing.JFrame {

    /**
     * Creates new form MedicineForm
     */
    public MedicineForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        show_medicine(); 
    }
    
    public ArrayList<Medicines> medicineList()
    {
        ArrayList<Medicines> medicinesList = new ArrayList<>();
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "SELECT * FROM medicine_table";
        try {
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery(query);
        
        Medicines medicines;
        while(rs.next())
        {
            medicines = new Medicines(rs.getString ("medicineID"), rs.getString ("medicineName"), rs.getString ("expiryDate"), rs.getString ("quantity"));
            medicinesList.add(medicines);
        }
        }catch(Exception e)
         {
           JOptionPane.showMessageDialog(null, e);
         }
        return medicinesList;
    }
    
    public void show_medicine()
    {
        ArrayList<Medicines> list = medicineList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[11];
        for(int i=0; i<list.size(); i++)
        {
            row[0] = list.get(i).getMedicinesID();
            row[1] = list.get(i).getMedicineName();
            row[2] = list.get(i).getExpiryDate();
            row[3] = list.get(i).getQuantity();
            model.addRow(row);   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jlblName = new javax.swing.JLabel();
        jlblQuantity = new javax.swing.JLabel();
        jtxtMedicineID = new javax.swing.JTextField();
        jtxtMedicineName = new javax.swing.JTextField();
        jtxtQuantity = new javax.swing.JTextField();
        jbtnSave = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jlblDate = new javax.swing.JLabel();
        jTxtDate = new javax.swing.JTextField();
        jBtnUpdate = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnBarChart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jlblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jlblTitle.setForeground(new java.awt.Color(0, 51, 102));
        jlblTitle.setText("MEDICINE");

        jlblID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblID.setText("Medicine ID");

        jlblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblName.setText("Medicine Name");

        jlblQuantity.setText("Quantity");

        jtxtMedicineID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMedicineIDActionPerformed(evt);
            }
        });

        jtxtMedicineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMedicineNameActionPerformed(evt);
            }
        });

        jtxtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuantityActionPerformed(evt);
            }
        });

        jbtnSave.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnSave.setText("INSERT");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(0, 0, 153));
        jbtnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setText("BACK");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jlblDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDate.setText("Expired Date");

        jTxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDateActionPerformed(evt);
            }
        });

        jBtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnUpdate.setText("UPDATE");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnDelete.setText("DELETE");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("(eg: M001)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("(yyyy-mm-dd)");

        jBtnBarChart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBarChart.setText("BAR CHART");
        jBtnBarChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBarChartActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "medicineID", "medicineName", "expiryDate", "quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblID)
                    .addComponent(jlblName)
                    .addComponent(jlblQuantity)
                    .addComponent(jbtnSave)
                    .addComponent(jlblDate))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtMedicineID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jBtnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnBarChart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnBack)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlblTitle)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMedicineID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblID)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblName))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jlblDate))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblQuantity))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnBack)
                    .addComponent(jBtnUpdate)
                    .addComponent(jBtnDelete)
                    .addComponent(jBtnBarChart))
                .addGap(221, 221, 221))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();

        jtxtMedicineID.setText(model.getValueAt(i,0).toString());
        jtxtMedicineName.setText(model.getValueAt(i,1).toString());
        jTxtDate.setText(model.getValueAt(i,2).toString());
        jtxtQuantity.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBtnBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBarChartActionPerformed
        try{
            String query = "SELECT medicineID, quantity FROM medicine_table";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(MySqlDatabase.ConnectDB(), query);
            JFreeChart chart = ChartFactory.createBarChart("Bar Chart", "medicineID", "quantity", (CategoryDataset) dataset, PlotOrientation.VERTICAL, false, true, true);

            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();

            ChartFrame frame = new ChartFrame("Bar Chart", chart);
            frame.setVisible(true);
            frame.setSize(840,840);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBtnBarChartActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "DELETE FROM medicine_table WHERE medicineID = ?";
        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jtxtMedicineID.getText());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data successfully deleted!");

            MedicineForm medicineForm = new MedicineForm();
            medicineForm.setVisible(true);
            dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        if(jtxtMedicineID.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection conn = MySqlDatabase.ConnectDB();

            try
            {
                UpdateQuery = "UPDATE medicine_table SET medicineName = ?, expiryDate = ?, quantity = ? WHERE medicineID = ?";
                ps = conn.prepareStatement(UpdateQuery);
                ps.setString(1, jtxtMedicineName.getText());
                ps.setString(2, jTxtDate.getText());
                ps.setString(3, jtxtQuantity.getText());

                ps.setString(4, jtxtMedicineID.getText());
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data successfully updated!");

                MedicineForm medicineForm = new MedicineForm();
                medicineForm.setVisible(true);
                dispose();
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Medicine ID you have enter does not found!");
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jTxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDateActionPerformed
        jTxtDate.setText(null);
    }//GEN-LAST:event_jTxtDateActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        NursePage nursePage = new NursePage();
        nursePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "INSERT INTO medicine_table(medicineID, medicineName, expiryDate, quantity)" + "VALUES (?,?,?,?)";
        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jtxtMedicineID.getText());
            ps.setString(2, jtxtMedicineName.getText());
            ps.setString(3, jTxtDate.getText());
            ps.setString(4, jtxtQuantity.getText());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data successfully insert.");

            MedicineForm medicineForm = new MedicineForm();
            medicineForm.setVisible(true);
            dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jtxtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuantityActionPerformed
        jtxtQuantity.setText(null);
    }//GEN-LAST:event_jtxtQuantityActionPerformed

    private void jtxtMedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMedicineNameActionPerformed
        jtxtMedicineName.setText(null);
    }//GEN-LAST:event_jtxtMedicineNameActionPerformed

    private void jtxtMedicineIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMedicineIDActionPerformed
        jtxtMedicineID.setText(null);
    }//GEN-LAST:event_jtxtMedicineIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBarChart;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtDate;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblQuantity;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextField jtxtMedicineID;
    private javax.swing.JTextField jtxtMedicineName;
    private javax.swing.JTextField jtxtQuantity;
    // End of variables declaration//GEN-END:variables
}
