/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.MySqlDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import javax.swing.table.TableModel;
import model.Registration;

/**
 *
 * @author Shazana Affandi
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        show_patient();
    }
    
    public ArrayList<Registration> patientList()
    {
        ArrayList<Registration> patientsList = new ArrayList<>();
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "SELECT * FROM patient_table";
        try {
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery(query);
        
        Registration registration;
        while(rs.next())
        {
            registration = new Registration(rs.getString ("patientID"), rs.getString ("patientName"), rs.getString ("icNumber"), rs.getString ("gender"), rs.getString ("date"), rs.getString ("address"), rs.getString ("mobilePhone"), rs.getString ("emailAddress"));
            patientsList.add(registration);
        }
        }catch(Exception e)
         {
           JOptionPane.showMessageDialog(null, e);
         }
        return patientsList;
    }
    
    public void show_patient()
    {
        ArrayList<Registration> list = patientList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[11];
        for(int i=0; i<list.size(); i++)
        {
            row[0] = list.get(i).getPatientID();
            row[1] = list.get(i).getPatientName();
            row[2] = list.get(i).getIcNumber();
            row[3] = list.get(i).getGender();
            row[4] = list.get(i).getDate();
            row[5] = list.get(i).getAddress();
            row[6] = list.get(i).getMobilePhone();
            row[7] = list.get(i).getEmailAddress();
            model.addRow(row);   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtICNo = new javax.swing.JTextField();
        jradBtnMale = new javax.swing.JRadioButton();
        jradBtnFemale = new javax.swing.JRadioButton();
        jtxtDate = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtMobilePhone = new javax.swing.JTextField();
        jtxtEmailAddress = new javax.swing.JTextField();
        jbtnInsert = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jlblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jlblTitle.setForeground(new java.awt.Color(0, 51, 102));
        jlblTitle.setText("PATIENT REGISTRATION");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Patient ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("IC No");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Patient Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mobile Phone");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Email Address");

        jtxtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPatientIDActionPerformed(evt);
            }
        });

        jtxtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPatientNameActionPerformed(evt);
            }
        });

        jtxtICNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtICNoActionPerformed(evt);
            }
        });

        jradBtnMale.setBackground(new java.awt.Color(0, 204, 204));
        jradBtnMale.setText("Male");
        jradBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradBtnMaleActionPerformed(evt);
            }
        });

        jradBtnFemale.setBackground(new java.awt.Color(0, 204, 204));
        jradBtnFemale.setText("Female");
        jradBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradBtnFemaleActionPerformed(evt);
            }
        });

        jtxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateActionPerformed(evt);
            }
        });

        jtxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddressActionPerformed(evt);
            }
        });

        jtxtMobilePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMobilePhoneActionPerformed(evt);
            }
        });

        jtxtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailAddressActionPerformed(evt);
            }
        });

        jbtnInsert.setBackground(new java.awt.Color(204, 204, 204));
        jbtnInsert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnInsert.setText("INSERT");
        jbtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(0, 0, 255));
        jbtnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setText("BACK");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnUpdate.setText("UPDATE ");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnDelete.setText("DELETE ");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("(eg: P001)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("(excluding '-' symbol)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("(yyyy-mm-dd)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("(excluding '-' symbol)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "patientID", "patientName", "icNumber", "gender", "date", "address", "mobilePhone", "emailAddress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlblTitle)
                .addGap(462, 462, 462))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2))
                                        .addGap(19, 19, 19))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtAddress)
                            .addComponent(jtxtEmailAddress)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jradBtnMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jradBtnFemale))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtMobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtICNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtxtPatientName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jbtnInsert)
                        .addGap(61, 61, 61)
                        .addComponent(jbtnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jbtnDelete)
                        .addGap(57, 57, 57)
                        .addComponent(jbtnBack)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlblTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtICNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jradBtnMale)
                            .addComponent(jradBtnFemale)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnBack)
                            .addComponent(jbtnDelete)
                            .addComponent(jbtnInsert)
                            .addComponent(jbtnUpdate)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPatientIDActionPerformed
        jtxtPatientID.setText(null);
    }//GEN-LAST:event_jtxtPatientIDActionPerformed

    private void jtxtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPatientNameActionPerformed
        jtxtPatientName.setText(null);
    }//GEN-LAST:event_jtxtPatientNameActionPerformed

    private void jtxtICNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtICNoActionPerformed
        jtxtICNo.setText(null);
    }//GEN-LAST:event_jtxtICNoActionPerformed

    private void jradBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradBtnMaleActionPerformed
        Gender = "Male";
    }//GEN-LAST:event_jradBtnMaleActionPerformed

    private void jradBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradBtnFemaleActionPerformed
        Gender = "Female";
    }//GEN-LAST:event_jradBtnFemaleActionPerformed

    private void jtxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateActionPerformed
        jtxtDate.setText(null);
    }//GEN-LAST:event_jtxtDateActionPerformed

    private void jtxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddressActionPerformed
        jtxtAddress.setText(null);
    }//GEN-LAST:event_jtxtAddressActionPerformed

    private void jtxtMobilePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMobilePhoneActionPerformed
        jtxtMobilePhone.setText(null);
    }//GEN-LAST:event_jtxtMobilePhoneActionPerformed

    private void jtxtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailAddressActionPerformed
        jtxtEmailAddress.setText(null);
    }//GEN-LAST:event_jtxtEmailAddressActionPerformed

    private void jbtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "INSERT INTO patient_table(patientID, patientName, icNumber, gender, date, address, mobilePhone, emailAddress)" + "values(?,?,?,?,?,?,?,?)";
        try{
            

            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jtxtPatientID.getText());
            ps.setString(2, jtxtPatientName.getText());
            ps.setString(3, jtxtICNo.getText());
            
            if(jradBtnMale.isSelected())
            {
                Gender = "Male";
            }
            if(jradBtnFemale.isSelected())
            {
                Gender = "Female";
            }
            ps.setString(4, Gender);
            
            ps.setString(5, jtxtDate.getText());
            ps.setString(6, jtxtAddress.getText());
            ps.setString(7, jtxtMobilePhone.getText());
            ps.setString(8, jtxtEmailAddress.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data successfully insert");
            
            RegisterForm registerForm = new RegisterForm();
            registerForm.setVisible(true);
            dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnInsertActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        NursePage nursePage = new NursePage();
        nursePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        if(jtxtPatientID.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection conn = MySqlDatabase.ConnectDB();
        
            try{
                UpdateQuery = "UPDATE patient_table SET patientName = ?, icNumber = ?, gender = ?, date = ?, address = ?, mobilePhone = ?, emailAddress = ? WHERE patientID = ?";
                ps = conn.prepareStatement(UpdateQuery);
                ps.setString(1, jtxtPatientName.getText());
                ps.setString(2, jtxtICNo.getText());
                
                if(jradBtnMale.isSelected())
                {
                    Gender = "Male";
                }
                if(jradBtnFemale.isSelected())
                {
                    Gender = "Female";
                }
                ps.setString(3, Gender);
                
                ps.setString(4, jtxtDate.getText());
                ps.setString(5, jtxtAddress.getText());
                ps.setString(6, jtxtMobilePhone.getText());
                ps.setString(7, jtxtEmailAddress.getText());
            
                ps.setString(8, jtxtPatientID.getText());
                ps.executeUpdate();
            
                JOptionPane.showMessageDialog(null, "Data Successfully Update!");
            
                RegisterForm registerForm = new RegisterForm();
                registerForm.setVisible(true);
                dispose();
            }catch(Exception e)
             {
                JOptionPane.showMessageDialog(null, e);
             }

        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "DELETE FROM patient_table WHERE patientID = ?";
        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jtxtPatientID.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data Successfully Deleted!");
            
            RegisterForm registerForm = new RegisterForm();
            registerForm.setVisible(true);
            dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int i = jTable1.getSelectedRow();
       TableModel model = jTable1.getModel();
        
       jtxtPatientID.setText(model.getValueAt(i,0).toString());
       jtxtPatientName.setText(model.getValueAt(i,1).toString());
       jtxtICNo.setText(model.getValueAt(i,2).toString());
       String Gender = model.getValueAt(i,3).toString();
        if (Gender.equals("Male"))
        {
            jradBtnMale.setSelected(true);
            jradBtnFemale.setSelected(false);
        }
        else
        {
            jradBtnFemale.setSelected(true);
            jradBtnMale.setSelected(false);
        }
       jtxtDate.setText(model.getValueAt(i,4).toString());
       jtxtAddress.setText(model.getValueAt(i,5).toString());
       jtxtMobilePhone.setText(model.getValueAt(i,6).toString());
       jtxtEmailAddress.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_jTable1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnInsert;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JRadioButton jradBtnFemale;
    private javax.swing.JRadioButton jradBtnMale;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtEmailAddress;
    private javax.swing.JTextField jtxtICNo;
    private javax.swing.JTextField jtxtMobilePhone;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    // End of variables declaration//GEN-END:variables

    private String Gender;
}