/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.MySqlDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import java.util.ArrayList;
import model.Treatment;


/**
 *
 * @author Shazana Affandi
 */
public class TreatmentForm extends javax.swing.JFrame {

    /**
     * Creates new form TreatmentForm
     */
    public TreatmentForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        updateCombo();
        show_treatment();
    }
    
    public ArrayList<Treatment> treatmentList()
    {
        ArrayList<Treatment> treatmentsList = new ArrayList<>();
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "SELECT * FROM treatment_table";
        try {
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery(query);
        
        Treatment treatment;
        while(rs.next())
        {
            treatment = new Treatment(rs.getString("treatmentNum"), rs.getString("date"), rs.getString("patientID"), rs.getString("patientName"), rs.getString("treatment"), rs.getString("medicines"));
            treatmentsList.add(treatment);
        }
        }catch(Exception e)
         {
           JOptionPane.showMessageDialog(null, e);
         }
        return treatmentsList;
    }
    
    public void show_treatment()
    {
        ArrayList<Treatment> list = treatmentList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[11];
        for(int i=0; i<list.size(); i++)
        {
            row[0] = list.get(i).getTreatmentNum();
            row[1] = list.get(i).getDate();
            row[2] = list.get(i).getPatientID();
            row[3] = list.get(i).getPatientName();
            row[4] = list.get(i).getTreatment();
            row[5] = list.get(i).getMedicines();
            model.addRow(row);   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jlblPatientID = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        jlblPatientName = new javax.swing.JLabel();
        jlblTreatment = new javax.swing.JLabel();
        jlblMedicines = new javax.swing.JLabel();
        jtxtDate = new javax.swing.JTextField();
        jtxtTreatment = new javax.swing.JTextField();
        jtxtMedicines = new javax.swing.JTextField();
        jbtnInsert = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jlblTreatmentNum = new javax.swing.JLabel();
        jtxtTreatmentNum = new javax.swing.JTextField();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jCmbBoxPatID = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCmbBoxPatName = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jlblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jlblTitle.setText("PATIENT'S TREATMENT");

        jlblPatientID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPatientID.setText("Patient ID");

        jlblDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDate.setText("Date");

        jlblPatientName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPatientName.setText("Patient Name");

        jlblTreatment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblTreatment.setText("Treatment");

        jlblMedicines.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblMedicines.setText("Medicines");

        jtxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateActionPerformed(evt);
            }
        });

        jtxtTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTreatmentActionPerformed(evt);
            }
        });

        jtxtMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMedicinesActionPerformed(evt);
            }
        });

        jbtnInsert.setBackground(new java.awt.Color(204, 204, 204));
        jbtnInsert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnInsert.setText("INSERT");
        jbtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(0, 0, 255));
        jbtnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setText("BACK");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jlblTreatmentNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblTreatmentNum.setText("Treatment Number");

        jtxtTreatmentNum.setText(" ");
        jtxtTreatmentNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTreatmentNumActionPerformed(evt);
            }
        });

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnUpdate.setText("UPDATE");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jCmbBoxPatID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jCmbBoxPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxPatIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("(eg: 1)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("(yyyy/mm/dd)");

        jCmbBoxPatName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "treatmentNum", "date", "patientID", "patientName", "treatment", "medicines"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(146, Short.MAX_VALUE)
                                .addComponent(jlblTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblPatientName)
                                            .addComponent(jlblPatientID)
                                            .addComponent(jlblTreatment)
                                            .addComponent(jlblMedicines))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCmbBoxPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jCmbBoxPatName, 0, 251, Short.MAX_VALUE)
                                                .addGap(21, 21, 21))
                                            .addComponent(jtxtTreatment)
                                            .addComponent(jtxtMedicines)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblTreatmentNum)
                                            .addComponent(jlblDate))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jtxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jtxtTreatmentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnInsert)
                        .addGap(49, 49, 49)
                        .addComponent(jbtnUpdate)
                        .addGap(47, 47, 47)
                        .addComponent(jbtnDelete)
                        .addGap(39, 39, 39)
                        .addComponent(jbtnBack)
                        .addGap(72, 72, 72)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jlblTitle)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTreatmentNum)
                            .addComponent(jtxtTreatmentNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblDate)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmbBoxPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPatientID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmbBoxPatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPatientName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTreatment))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblMedicines))
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUpdate)
                    .addComponent(jbtnBack)
                    .addComponent(jbtnInsert)
                    .addComponent(jbtnDelete))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateActionPerformed
        jtxtDate.setText(null);
    }//GEN-LAST:event_jtxtDateActionPerformed

    private void jtxtTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTreatmentActionPerformed
        jtxtTreatment.setText(null);
    }//GEN-LAST:event_jtxtTreatmentActionPerformed

    private void jtxtMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMedicinesActionPerformed
        jtxtMedicines.setText(null);
    }//GEN-LAST:event_jtxtMedicinesActionPerformed

    private void jbtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "INSERT INTO treatment_table(treatmentNum, date, patientID, patientName, treatment, medicines)" + "values(?,?,?,?,?,?)";
        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jtxtTreatmentNum.getText());
            ps.setString(2, jtxtDate.getText());
            ps.setString(3, (String) jCmbBoxPatID.getSelectedItem());
            ps.setString(4, (String) jCmbBoxPatName.getSelectedItem());
            ps.setString(5, jtxtTreatment.getText());
            ps.setString(6, jtxtMedicines.getText());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Insertion Successful");
            
            TreatmentForm treatmentForm = new TreatmentForm();
            treatmentForm.setVisible(true);
            dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnInsertActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        DentistPage dentistPage = new DentistPage();
        dentistPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jtxtTreatmentNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTreatmentNumActionPerformed
        jtxtTreatmentNum.setText(null);
    }//GEN-LAST:event_jtxtTreatmentNumActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
    if(jtxtTreatmentNum.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection conn = MySqlDatabase.ConnectDB();
      
            try{
                UpdateQuery = "UPDATE treatment_table SET date = ?, patientID = ?, patientName = ?, treatment = ?, medicines = ? WHERE treatmentNum = ?";
                ps = conn.prepareStatement(UpdateQuery);
                ps.setString(1, jtxtDate.getText());
                ps.setString(2, (String) jCmbBoxPatID.getSelectedItem());
                ps.setString(3, (String) jCmbBoxPatName.getSelectedItem());
                ps.setString(4, jtxtTreatment.getText());
                ps.setString(5, jtxtMedicines.getText());
                
                ps.setString(6, jtxtTreatmentNum.getText());
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Successfully update the data.");
                
                TreatmentForm treatmentForm = new TreatmentForm();
                treatmentForm.setVisible(true);
                dispose();
            }catch(Exception e)
             {
                JOptionPane.showMessageDialog(null, e);
             }
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "DELETE FROM treatment_table WHERE treatmentNum = ?";
        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jtxtTreatmentNum.getText());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Successfully deleted the data.");
            
            TreatmentForm treatmentForm = new TreatmentForm();
            treatmentForm.setVisible(true);
            dispose();
        }catch(Exception e)
         {
            JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jCmbBoxPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxPatIDActionPerformed

    }//GEN-LAST:event_jCmbBoxPatIDActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        jtxtTreatmentNum.setText(model.getValueAt(i,0).toString());
        jtxtDate.setText(model.getValueAt(i,1).toString());
        jCmbBoxPatID.setSelectedItem(model.getValueAt(i,2).toString());
        jCmbBoxPatName.setSelectedItem(model.getValueAt(i,3).toString());
        jtxtTreatment.setText(model.getValueAt(i,4).toString());
        jtxtMedicines.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateCombo() {
        Connection conn = MySqlDatabase.ConnectDB();
        String query = "SELECT * FROM patient_table";
        try{
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next())
            {
                jCmbBoxPatID.addItem(rs.getString("patientID"));
            }
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
        
        String query3 = "SELECT * FROM patient_table";
        try{
            PreparedStatement ps = conn.prepareStatement(query3);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next())
            {
                jCmbBoxPatName.addItem(rs.getString("patientName"));
            }
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreatmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCmbBoxPatID;
    private javax.swing.JComboBox<String> jCmbBoxPatName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnInsert;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblMedicines;
    private javax.swing.JLabel jlblPatientID;
    private javax.swing.JLabel jlblPatientName;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlblTreatment;
    private javax.swing.JLabel jlblTreatmentNum;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtMedicines;
    private javax.swing.JTextField jtxtTreatment;
    private javax.swing.JTextField jtxtTreatmentNum;
    // End of variables declaration//GEN-END:variables
}
